feat: implement frontend
jriedel-ionos/rampup-challenge-grpc pull request #1
Opened 2023-07-04 12:40 UTC by jriedel-ionos

2023-07-04 13:02 UTC, avorima requested changes

2023-07-04 13:02 UTC, avorima commented on frontend/frontend.go
> +		tmpl, err := template.ParseFiles("index.html")
```
2023/07/04 14:59:37 Failed to parse template: open index.html: no such file or directory
```

I would recommend you either embed the file or ensure that the path always is found

2023-07-04 13:52 UTC, avorima commented on frontend/frontend.go
> +		tmpl, err := template.ParseFiles("index.html")
You just changed the error message, but the bug is still there

2023-07-04 13:54 UTC, avorima requested changes

2023-07-04 14:36 UTC, avorima requested changes
Verify your code before pushing. This includes linting and testing

2023-07-04 14:36 UTC, avorima commented on frontend/frontend.go
> +		tmpl, err := template.ParseFS(templateFile, "index.html")
Don't parse the template on every request. It will never change as long as the app is running

2023-07-04 14:36 UTC, avorima commented on frontend/frontend.go
> +	log.Fatal(http.ListenAndServe(":8081", nil))
The port should probably be configurable

2023-07-04 14:36 UTC, avorima commented on server/server.go
>  	"rampup-challenge/server/pb"
Please run the linter again

2023-07-04 14:44 UTC, jriedel-ionos commented on server/server.go
>  	"rampup-challenge/server/pb"
it prints following 
```
server/server.go:9: File is not `gci`-ed with --skip-generated -s standard -s default (gci)
	"rampup-challenge/server/pb"
server/server.go:12: File is not `gci`-ed with --skip-generated -s standard -s default (gci)
	"google.golang.org/grpc/reflection"
```
i don't understand fully whats the problem tbh.

2023-07-04 14:45 UTC, avorima commented on server/server.go
>  	"rampup-challenge/server/pb"
`golangci-lint run --fix` is your friend in cases like these

2023-07-05 08:20 UTC, avorima requested changes

2023-07-05 08:20 UTC, avorima commented on frontend/frontend.go
> +	log.Println("Frontend server started on port " + Port)
Just a general thing: Prefer format string over this string concatenation. Same for things like printing errors, use `%v`

2023-07-05 08:20 UTC, avorima commented on frontend/frontend.go
> +	const Port = "8081"
That's not configurable

2023-07-05 08:25 UTC, jriedel-ionos commented on frontend/frontend.go
> +	const Port = "8081"
you mean for example by env variable?

2023-07-05 08:28 UTC, avorima commented on frontend/frontend.go
> +	const Port = "8081"
that would be one option. i was thinking about command-line flags

2023-07-05 08:42 UTC, avorima requested changes
Just fyi, the single hyphen may be printed in the help but the flag library can also handle the usual `--`

2023-07-05 08:42 UTC, avorima commented on frontend/frontend.go
> +	port := flag.String("port", "8081", "running port for the frontend")
Ports are numbers. And you're also using this port for listening

2023-07-05 09:53 UTC, avorima requested changes

2023-07-05 09:53 UTC, avorima commented on server/server.go
>  	fmt.Println(value)
Use log. fmt in server logs always looks like debugging leftovers

2023-07-05 09:53 UTC, avorima commented on frontend/frontend.go
> +		value := os.Getenv(varName)
Sorry, I completely overlooked this. The frontend is supposed to get this value from the backend

2023-07-05 11:21 UTC, avorima requested changes

2023-07-05 11:21 UTC, avorima commented on frontend/frontend.go
> +	// TODO get configured port from backend, not hardcoded
I don't understand this TODO. The address is configured by the flag

2023-07-05 11:21 UTC, avorima commented on frontend/frontend.go
> +		log.Printf("Failed to start backend server: %v", err)
If the linter tells you something is wrong, you shouldn't circumvent it by changing behavior. Figure out a way to use Fatalf here and still make use of defer without any warnings

2023-07-05 11:29 UTC, jriedel-ionos commented on frontend/frontend.go
> +	// TODO get configured port from backend, not hardcoded
i thought about automatically importing the port from backend, but it doesn't make sense tbh.

2023-07-05 11:46 UTC, jriedel-ionos commented on frontend/frontend.go
> +		log.Printf("Failed to start backend server: %v", err)
there is an approach (https://github.com/go-critic/go-critic/issues/1022) but i personally think it's pretty ugly. do you have another solution, or should i implement this approach?

2023-07-05 12:23 UTC, avorima requested changes

2023-07-05 12:23 UTC, avorima commented on frontend/frontend.go
> +			log.Println("Exiting due to error")
You're not exiting here

2023-07-05 13:36 UTC, merged